# Definindo o nome do workflow
name: CI/CD Pipeline

# Definindo quando o workflow será executado
on:
  push:
    branches: ['main', 'developer']

# Definindo os jobs que o workflow executará
jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Step 01
        run: echo Olá! Estou simulando um step 01!

      - name: Step 02
        run: echo Olá! Estou simulando um step 02!

      - name: Step 02
        run: echo Olá! Estou simulando um step 02!
